# ------------------------------------------
# AI vs Human Text Detector with Confidence
# ------------------------------------------
from flask import Flask, request, jsonify, render_template
from openai import OpenAI
import os

# Initialize Flask and OpenAI
app = Flask(__name__)
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY") or "YOUR_API_KEY_HERE")

# ------------------------------------------
# Function to analyze text
# ------------------------------------------
def detect_ai_text(text):
    """
    Uses OpenAI to determine whether the text seems AI-generated or human-written,
    along with a confidence score.
    """
    prompt = f"""
    You are an AI text detector.
    Analyze the text below and decide if it was written by a human or generated by AI.

    Text:
    \"\"\"{text}\"\"\"

    Respond strictly in JSON format like this:
    {{
      "result": "AI-generated" or "Human-written",
      "confidence": <a number between 0 and 100>
    }}
    """

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}],
        temperature=0
    )

    # Parse JSON safely
    import json
    try:
        data = json.loads(response.choices[0].message.content)
    except:
        data = {"result": "Unknown", "confidence": 0}

    return data

# ------------------------------------------
# Routes
# ------------------------------------------
@app.route('/')
def home():
    return render_template('index.html')

@app.route('/detect', methods=['POST'])
def detect():
    data = request.get_json()
    text = data.get('text', '')
    result = detect_ai_text(text)
    return jsonify(result)

# ------------------------------------------
# Run Flask app
# ------------------------------------------
if __name__ == '__main__':
    app.run(debug=True)
